name: log_collector
description: Provides log filtering, buffering, and retry.
homepage: https://github.com/housmart/log_collector
version: 1.0.3

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  path_provider:
  synchronized:

dev_dependencies:
  flutter_test:
    sdk: flutter
